version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: file-browser_server_1
      APP_PORT: 80
    container_name: file-browser_app_proxy_1
  server:
    image: >-
      filebrowser/filebrowser:v2.32.0@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/filebrowser.db:/database/filebrowser.db
      - ${UMBREL_ROOT}/home:/data
    environment:
      - FB_PORT=80
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/data
      - FB_NOAUTH=true
    container_name: file-browser_server_1
